version: '3.8'  # Use a supported version
services:
  fsb:
    image: ghcr.io/everythingsuckz/fsb:latest
    env_file:
      - ./fsb.env  # Path to the environment file
    ports:
      - "8080:8080"  # Example port mapping; modify as needed
    restart: unless-stopped
